#!/usr/bin/env bash
#    ScreenshotBASH-Endpoint-PHP
#    Copyright (C) 2018 Sefa Eyeoglu <contact@scrumplex.net> (https://scrumplex.net)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>.
set -e

function dialog_error {
    if [ -x "$(command -v kdialog)" ]; then
        kdialog --error "$@"
    elif [ -x "$(command -v zenity)" ]; then
        zenity --error --text "$@"
    else
        >&2 echo "No GUI Dialog application available. Please install zenity or kdialog."
        exit 1
    fi
}

DIR=$(dirname "$0")

# Exit if already running
pgrep spectacle && exit 0
pgrep gnome-screenshot && exit 0

source "$DIR/config"

if [ -x "$(command -v spectacle)" ]; then
    spectacle -r -b -n -o "$TARGET_FILENAME"
elif [ -x "$(command -v gnome-screenshot)" ]; then
    gnome-screenshot -a -f "$TARGET_FILENAME"
else
    dialog_error "No screenshot tool available! Please install KDE-Spectacle or GNOME-Screenshot."
    exit 1
fi

set +e
RESULT=$($DIR/uploadBASH $TARGET_FILENAME 2>&1)

if [ ! $? -eq 0 ]; then
    dialog_error "Uploading failed: $RESULT"
    exit 1
fi
set -e

xdg-open "$RESULT"

echo "$RESULT" | xsel -bsp

play "$DIR/completed.wav"

echo "$RESULT"
